### ISSUE TITLE
Refine IBC Integrations

### ISSUE THREAD

**Issue by ejmg** [penumbra-zone/cuiloa#196]
# Summary

Currently, there are extremely minimal offerings for IBC Clients, Channels, and Connections on Cuiloa. You can see a list of each type and which ones are associated with each other. However, this leaves users with little transparency w.r.t. the state of e.g. an IBC channel and any transactions that may have occurred over it. Similarly, nothing is shown for the state, response, and status of the counter-party. Other details, like the expiration of a given client are also completely unavailable.

In addition to this, details like individual connections and the explicit enumeration of all related IBC entities is largely unnecessary. IBC Channels are primarily the object of interest for a user that wants to see what IBC integrations are established between Penumbra and counter-party chains and the status of any previous/on-going IBC transactions.

## Sub-tasks

- [ ] IBC Clients and Connections should be largely de-prioritized as individual routes
- [ ] Channels should be expanded and re-worked to include the following:
  - [ ] Provide information on the relevant counter-party chain
  - [ ] Enumerate and make transparent the state and progress of transactions that occur over IBC Channels
    - [ ] expand (de)serialization for IBC events
    - [ ] expose counter-party information and events
