### ISSUE TITLE
Tweak organization of current pages

### ISSUE THREAD

**Issue by hdevalence** [penumbra-zone/cuiloa#6]
The current page structure should be tweaked to more cleanly separate different kinds of content.

### Current

Currently, the landing page `/` has a search bar and a list of recent transactions. The list has a height, time, and transaction hash. The height links to a block page and the hash links to a transaction page. Searching supports heights or tx hashes, and goes directly to the result page.

### Improved

- [x] Move the existing recent transactions list content off of the landing page and onto a "Transactions" page, at `/transactions/`. Update the existing `/tx` route to `/transaction`, for consistency (since `/tx` is sort of fine on its own, but `/txs` is less clear than `/transactions`).
- [x] Add a `/blocks` page to list recent blocks.
- [x] Change the landing page to have links to `/transactions` and `/blocks`. We will add more views later (e.g., IBC data), so I think it's fine for the landing page to just link out to the "topic"/"list" pages.
- [x] The `/block/HEIGHT` page currently shows the contents of transactions within the block. Instead, it should show (only):
  - [x] a list of transaction hashes, each linking to the respective transaction page
  - [x] a table of the raw ABCI events occurring in the context of the block (**not** in the context of a transaction within the block). At this stage, the table should not attempt to parse or interpret the events.
- [x] The `/transaction/HASH` page should also be tidied up, so that:
  - [x] The transaction JSON view should be expanded by default, rather than hiding the react-json-view component
  - [x] The block height should link to the block page
  - [x] it shows a table of all of the raw ABCI events occurring in the context of the transaction. Currently, some of them (the note commitments) are handled specially, but at this stage, we should just show the raw events, and not attempt to parse or interpret them.
- [x] Search results should go to `/search?q=...` with a list of results, even if there is only one result, so that we will be set up to handle multiple "search engines" for more complex queries (like "what are transactions that affect this IBC client?")

**Comment by ejmg** [comment]
closed by #73
